#
#  Author: Hari Sekhon
#  Date: 2022-01-27 18:55:16 +0000 (Thu, 27 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Docker Build Debian Java

on:
  push:
    branches:
      - master
      - main
    paths:
      - debian-java/**
      - .github/workflows/docker_build_debian_java.yaml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  docker_build:
    name: Docker Build
    uses: HariSekhon/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo_tags: |
        harisekhon/debian-java:latest
        ghcr.io/harisekhon/debian-java:latest
      context: debian-java
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
